(require :sb-bsd-sockets)
(require :asdf)
(load "src/packages.lisp")
(load "src/ansi.lisp")
(load "src/player.lisp")
(load "src/inventory.lisp")
(load "src/world.lisp")
(load "src/mob.lisp")
(load "src/combat.lisp")
(load "src/quest.lisp")
(handler-case
	(let ((*load-verbose* t)
		  (*load-print* t))
	  (load "src/server/core.lisp"))
  (error (e)
	(format t "LOAD ERROR: ~a~%" e)))
(multiple-value-bind (ann-sym ann-status)
		(find-symbol "ANNOUNCE-TO-ROOM" "MUD.SERVER")
(multiple-value-bind (send-sym send-status)
    (find-symbol "SEND-ROOM-OVERVIEW" "MUD.SERVER")
  (format t "announce symbol: ~a status: ~a fboundp: ~a macro? ~a~%"
	  ann-sym ann-status (and ann-sym (fboundp ann-sym))
	  (and ann-sym (macro-function ann-sym)))
  (format t "send-room-overview symbol: ~a status: ~a fboundp: ~a~%"
	  send-sym send-status (and send-sym (fboundp send-sym)))))
(sb-ext:exit)
